language: node_js
node_js:
  - "node"

after_script:
  - gitbook install
  - cp -r node_modules 3.9/
  - cp -r node_modules 2.9/
  - gitbook build 3.9/ _book
  - gitbook build 2.9/ _book/2.9/
  - grunt minify
  - cp CNAME _book
  - cd _book
  - git init
  - git config user.name "${USER_NAME}"
  - git config user.email "${USER_EMAIL}"
  - git add .
  - git commit -m "publish gitbook"
  - git push --force --quiet "https://${ACC_TOKEN}@${GH_REF}" master:${BRANCH}

branches:
  only:
    - master
